### ISSUE TITLE
Release 0.1.1

### ISSUE THREAD

**Issue by rodolfocarobene** [qiboteam/qibosoq#101]
Hi! I would proceed with a release so that there is a fixed version qibosoq on pypi that could support the ZCU208.

After that I will update qibosoq to the latest version of QICK so that it will be compatible with the new firmware @JavierSerranoGarcia is using.

Can I proceed with the release @scarrazza?

**Comment by scarrazza** [comment]
Sure, please go ahead.

**Comment by rodolfocarobene** [comment]
I did the release, but the deployment of the documentation failed... it says that
```
Tag "v0.1.1" is not allowed to deploy to github-pages due to environment protection rules.
```

**Comment by scarrazza** [comment]
Should be fixed now, could you please rerun the workflow for doc deployment?

**Comment by rodolfocarobene** [comment]
Thanks, now it works! (sorry for the late reply, but I didn't get any notification since the issue was closed)
