### ISSUE TITLE
Flux and drive  lines in ZCU111 board

### ISSUE THREAD

**Issue by JavierSerranoGarcia** [qiboteam/qibosoq#120]
Hi @rodolfocarobene,  
According to the platform for the ZCU111

  # Create channel objects
    channels = ChannelMap()
    channels |= Channel("L3-30_ro", port=controller.ports(6))  # readout  dac6
    # QUBIT 0
    channels |= Channel("L2-4-RO_0", port=controller.ports(0))  # feedback adc0
    channels |= Channel("L4-29_qd", port=controller.ports(3))  # drive    dac3
    channels |= Channel("L1-22_fl", port=controller.ports(0))  # flux     dac0
    # QUBIT 1
    channels |= Channel("L2-4-RO_1", port=controller.ports(1))  # feedback adc1
    channels |= Channel("L4-30_qd", port=controller.ports(4))  # drive    dac4
    channels |= Channel("L1-23_fl", port=controller.ports(1))  # flux     dac1
    # QUBIT 2
    channels |= Channel("L2-4-RO_2", port=controller.ports(2))  # feedback adc2
    channels |= Channel("L4-31_qd", port=controller.ports(5))  # drive    dac5
    channels |= Channel("L1-24_fl", port=controller.ports(2))  # flux     dac2

we use channels 3,4,5 for drive lines. But these channels are filtered, 3 and 4 in the range 1-4 Ghz and 5 in the range 0-1 GHz. 

Is that the right setup?

To confirm, channel 0,1,2 for the flux lines must be converted to single-end signals through the differential amplifiers we have.

Best Javi

**Comment by rodolfocarobene** [comment]
> we use channels 3,4,5 for drive lines. But these channels are filtered, 3 and 4 in the range 1-4 Ghz and 5 in the range 0-1 GHz.
Is that the right setup?

What do you mean that these are filtered? If I remember correctly there where no particular filter on the XM500 for the ZCU111. Or are you considering the ZCU216?

I'm not completely sure that this was the exact same setup, but I'm afraid it's the best I can provide

> To confirm, channel 0,1,2 for the flux lines must be converted to single-end signals through the differential amplifiers we have.

That I fully agree

**Comment by JavierSerranoGarcia** [comment]
Hi @rodolfocarobene,  as you can see in the next image, channels 3,4 are connected to HF device  and 5,6 to a LF device, everyone with different frequency response. 

![image](https://github.com/qiboteam/qibosoq/assets/9057076/38f9a91e-0fd5-49d1-a7be-9ff6cb6cbc71)


Channels 3,4 looks suitable for drive but 5, did not give you any problem for drive?

Regarding the readout, the local oscillator and the mixers, did you just connect the probe and the feedback signals to the I in the mixers or you did something different with the Q?

**Comment by rodolfocarobene** [comment]
I'm not sure that these connections are correct, but I'm completely sure that we were able to do three qubit spectroscopy at the same time... so I would say that that was not a problem.

Regarding up conversion, I just connected the I component while terminating at 50 ohm the Q.
