### ISSUE TITLE
Global QickSoc() objects

### ISSUE THREAD

**Issue by rodolfocarobene** [qiboteam/qibosoq#19]
Following the discussion in #11 
The  `QickSoc` object is global and we should instead pass it as an argument to the handler

**Comment by AleCandido** [comment]
The `RequestHandler` has access to the server instance through the `self.server` reference:
```py
[ins] In [10]: class Handler(BaseRequestHandler):
          ...:     def handle(self):
          ...:         self.server.ciaocome += 1
          ...:         print(self.server.ciaocome)
          ...:

[ins] In [11]: with TCPServer(("localhost", 9999), Handler) as server:
          ...:     server.ciaocome = 4
          ...:     server.serve_forever()
          ...:
5
6
7
8
```

So you could use to set simply `server.qicksoc = QickSoc()` and access inside the handler with `self.server.qicksoc`.
