### ISSUE TITLE
First release

### ISSUE THREAD

**Issue by AleCandido** [qiboteam/qibosoq#44]
I've just noticed we've never tagged Qibosoq.

Since it's proven working, and we start using this even in other places, I'd suggest tagging the current status of `main` (once properly tested), and release `0.0.1` on PyPI.

```[tasklist]
- [x] test current version on QPU
- [x] double check releasing workflow
- [x] tag
```

**Comment by scarrazza** [comment]
Sounds good to me.

**Comment by rodolfocarobene** [comment]
Current main has been tested and (almost) everything seems to be working.
Just one thing that I had committed and not pushed in the two-qubits-gate PR... #45 solves an issue encountered in https://github.com/qiboteam/qibolab/pull/474

Other than that, I am not aware of any bug lefts and all the main functionalities are implemented, so I agree that it's time for a release!

**Comment by rodolfocarobene** [comment]
Now I thing everything is ready :-)

**Comment by AleCandido** [comment]
I checked the workflow, it should be fine (exactly mirroring Qibolab's one, with the addition of py3.8 on Ubuntu).

Please, keep going with the tag.

In case of doubts:
```sh
git tag v0.0.1 -m "<your-description>"
git push --tags
```

**Comment by scarrazza** [comment]
Let me know when you are ready for a pypi release, I will take care of it.

**Comment by rodolfocarobene** [comment]
Sorry for the delay, I've now uploaded the tag 

thanks for the help :-)

**Comment by AleCandido** [comment]
@scarrazza: actually, I forgot we are deploying on releases, not tags.

So it didn't even fail. We just need to upload on PyPI the first tag :)

**Comment by scarrazza** [comment]
We must create a github release before uploading the artifacts manually to PYPI, this will generate a Zenodo DOI.

**Comment by AleCandido** [comment]
Can you install https://github.com/marketplace/actions/release-drafter on this repo?

**Comment by scarrazza** [comment]
Already installed since the creation of this repo.

**Comment by scarrazza** [comment]
For the first release you can click on the generate release notes:
![image](https://github.com/qiboteam/qibosoq/assets/10464827/a010af82-b305-46ae-a2c2-0d9d2d4acbf9)

**Comment by AleCandido** [comment]
I see, it has been a while since the last time I've done manually...

**Comment by scarrazza** [comment]
Make sure to erase and regenerate with button, even if #46 was merged, quite frequently it misses some stuff.

**Comment by AleCandido** [comment]
I used the button, but it could have been not visible before since I automatically set as pre-release (since 0.0.x ...).

But then I checked Qibolab, and I removed the pre-release label.
Do you still see problems with Zenodo?

**Comment by scarrazza** [comment]
Ready: https://pypi.org/project/qibosoq/0.0.1/
