### ISSUE TITLE
Releasing workflow on tags

### ISSUE THREAD

**Issue by AleCandido** [qiboteam/qibosoq#55]
In light of a faster iterative workflow, I'd propose to release wheels for each tag, essentially replacing `github.event_name == 'release' && github.event.action == 'published'` in:
https://github.com/qiboteam/qibosoq/blob/af13fbbdfff786cd967ce5ddc862cad4ff4cd93b/.github/workflows/deploy.yml#L23
with `github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')`.

and changing the event:
https://github.com/qiboteam/qibosoq/blob/af13fbbdfff786cd967ce5ddc862cad4ff4cd93b/.github/workflows/deploy.yml#L3-L8
to just:
```
 on: 
   push:
```

**Comment by rodolfocarobene** [comment]
It makes sense for me! In this way we could still do "releases" every once in a while but it should ease the qibosoq-qibolab development
