### ISSUE TITLE
Mypy import error

### ISSUE THREAD

**Issue by rodolfocarobene** [qiboteam/qibosoq#79]
Running `mypy src` on qibolab, I get various errors. Among them, one is:
```
src/qibolab/instruments/rfsoc/driver.py:8: error: 
Skipping analyzing "qibosoq": module is installed, but missing library stubs or py.typed marker  [import]
```
Clearly it's not a big problem, but why is it like this? Should we do something to fix it?
I think adding a `py.typed` file to `src/qibosoq` fixed the problem, but I don't have much experience and I don't know if this is something to do.

Do you, @AleCandido, know something more about this?

**Comment by AleCandido** [comment]
Yes, that's the proper way of doing it. I had not thought yet about seriously distributing types, it was more for internal use. But now that you took the burden of properly run Mypy and extensively introducing types in Qibosoq, it is fair to even properly distribute them.

https://peps.python.org/pep-0561/#packaging-type-information
(the PEP contemplates even the case of stubs, but we're only interested in inline types)
